# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1072, 724)
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(0, 30, 831, 691))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.dirLineEdit = QtWidgets.QLineEdit(Dialog)
        self.dirLineEdit.setGeometry(QtCore.QRect(90, 0, 621, 31))
        self.dirLineEdit.setObjectName("dirLineEdit")
        self.upButton = QtWidgets.QPushButton(Dialog)
        self.upButton.setGeometry(QtCore.QRect(712, 0, 121, 31))
        self.upButton.setObjectName("upButton")
        self.backButton = QtWidgets.QPushButton(Dialog)
        self.backButton.setGeometry(QtCore.QRect(0, 0, 93, 31))
        self.backButton.setObjectName("backButton")
        self.splitter_3 = QtWidgets.QSplitter(Dialog)
        self.splitter_3.setGeometry(QtCore.QRect(830, 0, 241, 121))
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.ipAddrLineEdit = QtWidgets.QLineEdit(self.splitter_3)
        self.ipAddrLineEdit.setObjectName("ipAddrLineEdit")
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_3)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.connectButton = QtWidgets.QPushButton(self.splitter_2)
        self.connectButton.setObjectName("connectButton")
        self.disconnectButton = QtWidgets.QPushButton(self.splitter_2)
        self.disconnectButton.setObjectName("disconnectButton")
        self.splitter = QtWidgets.QSplitter(self.splitter_3)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.startServerButton = QtWidgets.QPushButton(self.splitter)
        self.startServerButton.setObjectName("startServerButton")
        self.stopServerButton = QtWidgets.QPushButton(self.splitter)
        self.stopServerButton.setObjectName("stopServerButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.upButton.setText(_translate("Dialog", "Up"))
        self.backButton.setText(_translate("Dialog", "back"))
        self.connectButton.setText(_translate("Dialog", "Connect"))
        self.disconnectButton.setText(_translate("Dialog", "Disconnect"))
        self.startServerButton.setText(_translate("Dialog", "Start Server"))
        self.stopServerButton.setText(_translate("Dialog", "Stop Server"))
